---
kind: pkgfile.Build
spec:
  targets:
    - sbc-allwinner
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.9.0-1-gb047e41
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
---
kind: common.Renovate
spec:
  packageRules:
    - matchPackageNames:
        - u-boot/u-boot
        - ARM-software/arm-trusted-firmware
      versioning: 'regex:^(?<major>\d+)\.(?<minor>\d+)\.?(?<patch>\d+)?$'
