# commit to be tagged for the new release
commit = "HEAD"

project_name = "sbc-allwinner"
github_repo = "siderolabs/sbc-allwinner"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.0"
pre_release = false

# [notes]
